// Mocks generated by Mockito 5.4.4 from annotations
// in cloudwalk_nasa_challenge/test/app/data/repositories/nasa_apod_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cloudwalk_nasa_challenge/app/data/datasources/nasa_apod_network_datasource.dart'
    as _i2;
import 'package:cloudwalk_nasa_challenge/app/data/models/nasa_apod.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NasaApodNetworkDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNasaApodNetworkDatasource extends _i1.Mock
    implements _i2.NasaApodNetworkDatasource {
  @override
  _i3.Future<List<_i4.NasaApod>> getNasaApodsFromDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNasaApodsFromDateRange,
          [
            startDate,
            endDate,
          ],
        ),
        returnValue: _i3.Future<List<_i4.NasaApod>>.value(<_i4.NasaApod>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.NasaApod>>.value(<_i4.NasaApod>[]),
      ) as _i3.Future<List<_i4.NasaApod>>);
}
