name: "Test and Build"

on:
  pull_request:

jobs:
  build:
    name: Test and Build
    runs-on: macos-latest

    steps:
      #1 Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

        #2 setup java
      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "17"

        #3 setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3"
          channel: "stable"

        #4 install dependencies
      - name: Install Dependencies
        run: flutter pub get

        #5 create .env file
      - name: Create .env file
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: |
          echo NASA_API_KEY=$NASA_API_KEY > .env
          cat .env

        #6 run test
      - name: Run unit tests
        run: flutter test

      - uses: futureware-tech/simulator-action@v3
        with:
          model: "iPhone 14"

        #7 run integration test
      - name: Run integration test
        run: flutter test integration_test

        #8 build apk
      - name: Build APK
        run: flutter build apk --release

        #9 build aab
      - name: Build appBundle
        run: flutter build appbundle

        #10 build ipa
      - name: Build IPA
        run: flutter build ipa --no-codesign
      - name: Compress Archives and IPAs
        run: |
          cd build
          tar -czf ios_build.tar.gz ios

        #11 upload build artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
            build/ios_build.tar.gz
